### ISSUE TITLE
Does not properly recognise the type of forwardRef components

### ISSUE THREAD

**Issue by colorninja** [TheSpicyMeatball/react-nanny#10]
When using components created using `forwardRef`, the nanny starts forgetting it's children and treats them as `undefined`!

Reproduced: https://codesandbox.io/s/dazzling-hodgkin-ntqiw?file=/src/App.tsx

Thanks for the library, it's great :)

**Comment by TheSpicyMeatball** [comment]
Very interesting! Thanks for the feedback. I'll look into it.

**Comment by TheSpicyMeatball** [comment]
@colorninja

I've now added support for `forwardRef` in v2.12.0. However due to the higher order component nature of `forwardRef`, the only way to reliably derive the type is with the [customTypeKey](https://www.npmjs.com/package/react-nanny#user-content-customtypekey) method. Otherwise, all components using `forwardRef` will be assumed to be the same. 

I hope this helps!

**Comment by Jonatthu** [comment]
@TheSpicyMeatball the funny part is that it works when you change it to:

InputRight is wrapper in a forwardRef and that was the only way to make it work without a custom key...
getChild(props.children, (x) => (x as any).type == InputRight); 

Is this somehow less performant that custom key? @TheSpicyMeatball
